### ISSUE TITLE
JavaScript is not pass-by-reference

### ISSUE THREAD

**Issue by mataslauzadis** [Drakador/CodeNotes#1]
https://github.com/Drakador/CodeNotes/blob/f1be48728cbe75d38e8acf3f36c862fa715b31d4/Javascript/NewJavascriptNotes.js#L20

https://www.javascripttutorial.net/javascript-pass-by-value/

**Comment by Drakador** [comment]
NewJavascriptNotes.js is removed with https://github.com/Drakador/CodeNotes/commit/3cd010c01048ab71c157542e60f78eead9d00b2f in favor of jsnotes.html
